version: '3.7'
services:
  redis:
    image: redis:6.2.0
    ports:
      - 6379:6379
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker:/docker-entrypoint-initaws.d
