version: '3.7'
services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,sqs
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./docker:/docker-entrypoint-initaws.d
