name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:15
    services:
      redis:
        image: redis:6.2.0
        ports:
          - 6379:6379
      localstack:
        image: localstack/localstack
        ports:
          - 4566:4566
        env:
          SERVICES: dynamodb,sqs
          HOSTNAME_EXTERNAL: localstack

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up node 15
        uses: actions/setup-node@v2.2.0
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn

      - name: Run all tests
        run: yarn test
        env:
          TS_NODE_PROJECT: tsconfig.json
          TS_NODE_TRANSPILE_ONLY: true
          REDIS_HOST: redis
          DOCKER_LOCALHOST: localstack
          AWS_ACCESS_KEY_ID: xxxx
          AWS_SECRET_ACCESS_KEY: xxx
